name: Code Analysis using Snyk
inputs:
  SnykToken:
    description: 'Snyk API Token'
    required: true
    default: 'Missing'
  Pipeline_Run:
    description: 'Pipeline Run'
    required: true
    default: 'snyk-report'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Authenticate Snyk
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.SnykToken }}
        SNYK_API: "https://api.eu.snyk.io"
      run: npx snyk auth $SNYK_TOKEN
    - name: Install Snyk Tools
      shell: bash
      run: npm install snyk-to-html -g
    - uses: snyk/actions/setup@master
    - name: Snyk Test
      shell: bash
      run: snyk code test
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
        SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
    - name: Snyk Report
      shell: bash
      run: snyk code test --json | snyk-to-html -o results-code-${{ inputs.Pipeline_Run }}.html
      continue-on-error: true # To make sure that SARIF upload gets called
    - name: Upload Code Scanning Result
      uses: actions/upload-artifact@v4
      with:
        name: snyk-scanning-results
        path: results-code-${{ inputs.Pipeline_Run }}.html
