name: Code Analysis using Snyk
description: "Performs code analysis using Snyk and generates a report."
inputs:
  SNYK_SECRET:
    description: "Snyk Service Account - Secret API Token"
    required: true
    default: "Missing"
  SNYK_CLIENT_ID:
    description: "Snyk Service Account - Client ID API Token"
    required: true
    default: "Missing"
  PIPELINE_RUN:
    description: "Pipeline Run"
    required: true
    default: "snyk-report"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setup snyk-to-html
      shell: bash
      run: npm install snyk-to-html -g
    - name: Setup API Endpoint for Snyk
      shell: bash
      env:
        SNYK_API: "https://api.eu.snyk.io"
      run: npx snyk config set endpoint=$SNYK_API
    - name: Authenticate Snyk
      shell: bash
      env:
        SNYK_SECRET: ${{ inputs.SNYK_SECRET }}
        SNYK_CLIENT_ID: ${{ inputs.SNYK_CLIENT_ID }}
      run: npx snyk auth --auth-type=oauth --client-secret=$SNYK_SECRET --client-id=$SNYK_CLIENT_ID
    - name: Install Snyk Tools
      shell: bash
      run: npm install snyk-to-html -g
    - uses: snyk/actions/setup@master
    - name: Snyk Test
      shell: bash
      run: snyk code test
      continue-on-error: true # To make sure that SARIF upload gets called
    - name: Snyk Report
      shell: bash
      run: snyk code test --json | snyk-to-html -o results-code-${{ inputs.PIPELINE_RUN }}.html
      continue-on-error: true # To make sure that SARIF upload gets called
    - name: Upload Code Scanning Result
      uses: actions/upload-artifact@v4
      with:
        name: snyk-scanning-results
        path: results-code-${{ inputs.PIPELINE_RUN }}.html