name: Code Analysis using Snyk

on: 
  push:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate Snyk
        run: npx snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Install Snyk Tools
        run: npm install snyk-to-html -g
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk code test
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Report
        run: snyk code test --json | snyk-to-html -o results-code-${{ github.run_id }}.html
      - name: Upload Code Scanning Result
        uses: actions/upload-artifact@v4
        with:
          name: snyk-scanning-results
          path: results-code-${{ github.run_id }}.html